---
# handlers file for nginx
  - name: Nginx start
    become: yes
    service: name=nginx state=started

  - name: Nginx restart
    become: yes
    service: name=nginx state=restarted

  - name: Nginx reload
    become: yes
    service: name=nginx state=reloaded

    
  - name: Update file
    copy:
      src: 'templates/service_state'
      dest: '/opt/service_state'
    become: yes